#!/bin/sh
set -e
mkdir .lock # w/ set -e, this will bail early as a kind of lock

PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags" "$dir/$$.cscope"' EXIT
git ls-files | \
  /usr/local/bin/ctags \
    -L - \
    -f "$dir/$$.tags" \
    --languages=-javascript,sql,d \
    --tag-relative=never
mv "$dir/$$.tags" "$dir/tags"

git ls-files \
    | awk '{print "\""$0"\""}' \
    | cscope -Rb \
    -f "$dir/$$.cscope" \
    -i -
mv "$dir/$$.cscope" "$dir/cscope.out"

rmdir .lock
